### ISSUE TITLE
ROS 2 Foxy - TOF ADTF3175 "Failed to read the imager type" 

### ISSUE THREAD

**Issue by LukasMacha97** [analogdevicesinc/tof-ros2#23]
I am currently trying to run the TOF ADTF3175 with ROS 2 Foxy on Ubuntu 20.04 however no matter what confi file or mode I try I get the following "Failed to read the imager type" error: 

```
[INFO] [launch]: All log files can be found below /home/lukas/.ros/log/2023-04-16-18-33-55-043016-lukas-5467
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tof_ros2cpp-1]: process started with pid [5469]
[tof_ros2cpp-1] I20230416 18:33:55.129343  5469 aditof_utils.cpp:91] Started camera intialization
[tof_ros2cpp-1] I20230416 18:33:55.129591  5469 system_impl.cpp:134] SDK built with websockets version:3.1.0
[tof_ros2cpp-1] I20230416 18:33:55.129657  5469 network_sensor_enumerator.cpp:57] Looking for sensors over network
[tof_ros2cpp-1] [2023/04/16 18:33:55:1297] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[tof_ros2cpp-1] Conn established
[tof_ros2cpp-1] Connection Closed
[tof_ros2cpp-1] I20230416 18:33:55.153599  5469 camera_itof.cpp:143] Initializing camera
[tof_ros2cpp-1] [2023/04/16 18:33:55:1536] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[tof_ros2cpp-1] Conn established
[tof_ros2cpp-1] E20230416 18:34:00.267035  5469 camera_itof.cpp:170] Failed to read the imager type
[tof_ros2cpp-1] E20230416 18:34:00.267273  5469 aditof_utils.cpp:118] Could not initialize camera!
[tof_ros2cpp-1] Connection Closed
[ERROR] [tof_ros2cpp-1]: process has died [pid 5469, exit code -11, cmd '/home/lukas/ros2_ws/install/tof_ros2cpp/lib/tof_ros2cpp/tof_ros2cpp ip=10.42.0.1 config_file=config/config_adsd3500_adsd3030_new_modes.json mode=3 --ros-args -r __node:=tof_ros2cpp'].
```

Any idea how to resolve this issue?

**Comment by dNechita** [comment]
Hi,
Error "Failed to read the imager type" suggests that the SDK on ADTF3175 board is too old for the SDK that you have your Ubuntu 20.04. Can you please update the SDK on the board to match the one on your PC?

**Comment by LukasMacha97** [comment]
Thanks, Dan,

Can you just note down few instructions - where do I find the SDK I should be using, how do I flash it to the board?

Thank you.

Best regards,
Lukas Macha

Lukas Macha > AAPS CDT Student, Cohort 2
----------------------------------------
E ***@***.******@***.***>
----------------------------------------
University of Bath >
Department of Mechanical Engineering, Claverton Down, BA2 7AY, United Kingdom
----------------------------------------
***@***.***


***@***.***


----------------------------------------

[Icon  Description automatically generated]<https://www.aaps-cdt.ac.uk/>                [A picture containing clipart  Description automatically generated] <https://twitter.com/AapsCdt>               [A picture containing text, clipart  Description automatically generated] <https://www.linkedin.com/company/aaps-cdt>

**Comment by LukasMacha97** [comment]
Thanks, @dNechita , I flashed the sd card and the fw_update using the 4.1.1 release and using the config_adsd_3500_3030_new_modes.json and the error is gone. 

However another error "Depth compute library not initialized" now popped up when I launch the camera_node

see log below, any suggestions on what I might have done wrong? 

[log.txt](https://github.com/analogdevicesinc/tof-ros2/files/11276752/log.txt)

Thank you

**Comment by dNechita** [comment]
Looking at the log, it looks like the ROS node is trying to set mode "qmp" while the SDK has updated the names of the modes (sr-native, lr-native, sr-qnative and lr-qnative).
@rbudai98 can you provide some help on this?

**Comment by rbudai98** [comment]
Hi!
Could you let us know if you used the pre generated libraries fot tof_lib or you built the SDK? In case it is usig the generated ones, than I might need some additional information. In case you are using the SDK with the flag following flag must be set to `DUSE_DEPTH_COMPUTE_OPENSOURCE=1`

Regarding the qmp, the ROS binding choses modes based on the retrieve available ones from the camera. (Since you are setting to qmp, I am not 100% sure that either the latest SD card image is used, or the right config file)

**Comment by rbudai98** [comment]
Hi, @LukasMacha97! Is there any update regarding the issue?

**Comment by LukasMacha97** [comment]
Hi, @rbudai98, thanks for the help, I tried flashing the sd card and the fw_update using the 4.1.1 release and using the config_adsd_3500_3030_new_modes.json with mode set to 0 and the device now works with the ROS 2 nodes.
