### ISSUE TITLE
colcon build error

### ISSUE THREAD

**Issue by Genozen** [analogdevicesinc/tof-ros2#55]
I've verified my ROS2 Humble works correctly.

When executing `colcon build` after installing the .deb dpkg

```
~
/Documents/ToF_ros2/src/tof-ros2/src/aditof_utils.cpp:117:30: error: no matching function for call to ‘aditof::Camera::initialize(std::string&)’
  117 |   status = camera->initialize(arguments[1]);
      |            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
~
---
Failed   <<< tof_ros2cpp [5.30s, exited with code 2]

Summary: 0 packages finished [5.95s]
  1 package failed: tof_ros2cpp
  1 package had stderr output: tof_ros2cpp

```

Any suggestions on how to fix this?

**Comment by Genozen** [comment]
I've modified the code to take no parameters on initialization. Not sure if this would cause a problem, but it did built...

Now I have error when doing the roslaunch or ros2 run

```
ros2 launch tof_ros2cpp EVAL-ADTF3175D.launch.xml
[INFO] [launch]: All log files can be found below /home/genozen/.ros/log/2023-12-19-02-24-37-373240-genozen-41279
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tof_ros2cpp_node-1]: process started with pid [41280]
[tof_ros2cpp_node-1] I20231219 02:24:37.489240 41280 aditof_utils.cpp:102] Started camera intialization
[tof_ros2cpp_node-1] I20231219 02:24:37.489605 41280 system_impl.cpp:92] SDK built with websockets version:3.1.0
[tof_ros2cpp_node-1] I20231219 02:24:37.489640 41280 network_sensor_enumerator.cpp:57] Looking for sensors over network: 10.42.0.1
[tof_ros2cpp_node-1] [2023/12/19 02:24:37:4897] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[tof_ros2cpp_node-1] Conn established
[tof_ros2cpp_node-1] Connection Closed
[tof_ros2cpp_node-1] I20231219 02:24:37.534282 41280 camera_itof.cpp:156] Initializing camera
[tof_ros2cpp_node-1] [2023/12/19 02:24:37:5343] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[tof_ros2cpp_node-1] Conn established
[tof_ros2cpp_node-1] I20231219 02:24:37.571247 41280 mode_info.cpp:138] Using new mixed modes table for ADSD3500 w/ADSD3100.
[tof_ros2cpp_node-1] I20231219 02:24:37.873131 41280 camera_itof.cpp:370] Current adsd3500 firmware version is: 4.6.0.0
[tof_ros2cpp_node-1] I20231219 02:24:37.873153 41280 camera_itof.cpp:372] Current adsd3500 firmware git hash is: 174f719c1df4140b704e48901adbbe556cc08fd9
[tof_ros2cpp_node-1] W20231219 02:24:37.873215 41280 camera_itof.cpp:469] fsyncMode is not being set by SDK.
[tof_ros2cpp_node-1] W20231219 02:24:37.873389 41280 camera_itof.cpp:479] mipiSpeed is not being set by SDK.
[tof_ros2cpp_node-1] W20231219 02:24:37.873405 41280 camera_itof.cpp:490] enableTempCompenstation is not being set by SDK.
[tof_ros2cpp_node-1] W20231219 02:24:37.873417 41280 camera_itof.cpp:500] enableMetaDatainAB is not being set by SDK.
[tof_ros2cpp_node-1] W20231219 02:24:37.873430 41280 camera_itof.cpp:510] enableEdgeConfidence is not being set by SDK.
[tof_ros2cpp_node-1] I20231219 02:24:37.873441 41280 camera_itof.cpp:514] Camera initialized
[tof_ros2cpp_node-1] I20231219 02:24:37.873482 41280 aditof_utils.cpp:511] SD card image version: microsd-4.3.0-08d887e8.img
[tof_ros2cpp_node-1] I20231219 02:24:37.873490 41280 aditof_utils.cpp:512] Kernel version: lf-5.10.72-2.2.0
[tof_ros2cpp_node-1] I20231219 02:24:37.873497 41280 aditof_utils.cpp:513] U-Boot version: imx_v2020.04_5.4.70_2.3.0
[tof_ros2cpp_node-1] E20231219 02:24:37.873540 41280 camera_itof.cpp:2209] Failed to open: 
[tof_ros2cpp_node-1] W20231219 02:24:37.873683 41280 camera_itof.cpp:2244] abThreshMin was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873706 41280 camera_itof.cpp:2251] confThresh was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873719 41280 camera_itof.cpp:2258] radialThreshMin was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873733 41280 camera_itof.cpp:2266] radialThreshMax was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873749 41280 camera_itof.cpp:2274] jblfWindowSize was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873761 41280 camera_itof.cpp:2283] jblfApplyFlag was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873776 41280 camera_itof.cpp:2291] fps was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873788 41280 camera_itof.cpp:2298] vcselDelay was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873808 41280 camera_itof.cpp:2305] jblfMaxEdgeThreshold was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873821 41280 camera_itof.cpp:2313] jblfABThreshold was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873834 41280 camera_itof.cpp:2320] jblfGaussianSigma was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873848 41280 camera_itof.cpp:2328] jblfExponentialTerm was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873862 41280 camera_itof.cpp:2336] enablePhaseInvalidation was not found in .ini file, not setting.
[tof_ros2cpp_node-1] W20231219 02:24:37.873881 41280 camera_itof.cpp:1726] bitsInPhaseOrDepth was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873896 41280 camera_itof.cpp:1741] bitsInConf was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873910 41280 camera_itof.cpp:1766] bitsInAB was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873922 41280 camera_itof.cpp:1775] partialDepthEnable was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873935 41280 camera_itof.cpp:1784] inputFormat was not found in .ini file
[tof_ros2cpp_node-1] W20231219 02:24:37.873948 41280 camera_itof.cpp:1793] xyzEnable was not found in .ini file
[tof_ros2cpp_node-1] I20231219 02:24:37.873962 41280 camera_itof.cpp:591] Chosen mode: sr-qnative
[tof_ros2cpp_node-1] I20231219 02:24:37.873970 41280 camera_itof.cpp:645] Using ini file: 
[tof_ros2cpp_node-1] E20231219 02:24:37.889019 41280 mode_info.cpp:208] Please set the number of bitsInAb in ini file!
[tof_ros2cpp_node-1] I20231219 02:24:37.889101 41280 camera_itof.cpp:1027] initComputeLibrary
[tof_ros2cpp_node-1] Failed to initialize Cal block
[tof_ros2cpp_node-1] E20231219 02:24:37.889127 41280 camera_itof.cpp:1079] InitTofiConfig failed
[tof_ros2cpp_node-1] E20231219 02:24:37.889145 41280 camera_itof.cpp:699] Initializing compute libraries failed.
[tof_ros2cpp_node-1] E20231219 02:24:37.889164 41280 aditof_utils.cpp:198] Could not set camera frame type!
[tof_ros2cpp_node-1] I20231219 02:24:38.252377 41280 aditof_utils.cpp:161] Camera started
[tof_ros2cpp_node-1] I20231219 02:24:38.253844 41280 publisher_factory.cpp:64] Added raw data publisher
[tof_ros2cpp_node-1] I20231219 02:24:38.254076 41280 publisher_factory.cpp:59] Added depth publisher
[tof_ros2cpp_node-1] I20231219 02:24:38.254318 41280 publisher_factory.cpp:75] Added conf data publisher
[tof_ros2cpp_node-1] E20231219 02:24:38.286264 41280 camera_itof.cpp:850] Depth compute libray not initialized
[tof_ros2cpp_node-1] E20231219 02:24:38.286314 41280 aditof_utils.cpp:295] Could not request frame!
[tof_ros2cpp_node-1] E20231219 02:24:38.377664 41280 camera_itof.cpp:850] Depth compute libray not initialized
[tof_ros2cpp_node-1] E20231219 02:24:38.377713 41280 aditof_utils.cpp:295] Could not request frame!
[tof_ros2cpp_node-1] E20231219 02:24:38.478062 41280 camera_itof.cpp:850] Depth compute libray not initialized
[tof_ros2cpp_node-1] E20231219 02:24:38.478116 41280 aditof_utils.cpp:295] Could not request frame!
[tof_ros2cpp_node-1] E20231219 02:24:38.577895 41280 camera_itof.cpp:850] Depth compute libray not initialized
[tof_ros2cpp_node-1] E20231219 02:24:38.577944 41280 aditof_utils.cpp:295] Could not request frame!

```

**Comment by rbudai98** [comment]
Hi @Genozen!
The problems seems to occure due to changes in the ToF SDK and not using the correct version for ROS2 node. There are two possible solutions for it (second one is advisable):

In case you have ToF SDK v4.3.0 or older, the previously mentioned function does not take any arguments, and you should use the same tag in ROS2, like: https://github.com/analogdevicesinc/tof-ros2/releases/tag/v4.3.0

However if you are using the latest ROS2 code, than make sure to update the ToF SDK to the latest master as well, ad the firstly mentioned error should not be valid anymore.

After solving the initial issue, the second mentioned problem should no longer be present.

**Comment by Genozen** [comment]
Hi @rbudai98, thank you for the swift reply!

I'm unfortunately still having trouble getting my ToF running in ROS 2...

I'll try to specify details on what I did exactly, could you help double-check if something looks wrong?

On my PC:
- Ubuntu 22.04
- ROS 2 Humble installed running correctly
- `TOF_Evaluation_Ubuntu_ADTF3175D-Rel4.3.0` installed correctly and running `./ADIToFGUI` show the ToF viewer and can see camera streaming and point cloud rendering.. (using this [guide](https://github.com/analogdevicesinc/ToF/releases/tag/v4.3.0) )

On the ADTF3175D Eval board:
- SD card image is flashed with `microsd-4.3.0-08d887e8.zip` generated from the `./get_image` on my Windows 11's `TOF_Evaluation_ADTF3175D-Rel4.3.0`
- Firmware loaded 4.6.0  (checked by ssh into the analog@10.42.0.1 and ran `./ctrl_app`

-------
Per #55 discussion, I was originally using your `main` branch when cloning.

Now, I've tried using the release tag you give, and tried to build from source and cloning from git, but yields same issue:

On my Linux PC:
I downloaded the Adsd3030 tof_lib for Ubuntu 22.04 and executed the `sudo dpkg -i tof_lib.deb`

Then,
`mkdir -p ToF_ros2/src`
`cd ToF_ros2/src`
`git clone --depth 1 --branch v4.3.0 https://github.com/analogdevicesinc/tof-ros2.git`
`cd ..`
`  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH;/opt/websockets/lib;/usr/local/lib"`
`colcon build`
`source install/setup.bash`

Built was successful, but executing these gave errors:
```
ros2 launch tof_ros2cpp EVAL-ADTF3175D.launch.xml
file 'EVAL-ADTF3175D.launch.xml' was not found in the share directory of package 'tof_ros2cpp' which is at '/home/Genozen/Documents/ToF_ros2_4.3.0/install/tof_ros2cpp/share/tof_ros2cpp'
```
The tof_ros2 for v4.3.0 does not have this launch file in the share nor in the src... but the main branch does.

And

`ros2 run tof_ros2cpp tof_ros2cpp_node ip=10.42.0.1 config_file=~/Analog Devices/TOF_Evaluation_Ubuntu_ADTF3175D-Rel4.3.0/bin_22.04/config/config_adsd3500_adsd3030.json mode=5 enable_multithread=true`

But resulted in `No executable found`


Also, side note. I don't see any ToF SDK newer than the v4.3.0 on their release page...

**Comment by rbudai98** [comment]
Thank you for the detailed response @Genozen.

Since you changed to tof-ros2 tag4.3.0 lets continue with that version. Also it did build, so that should be a good starting point. I suppose after your build you did use the general:
`source install/local_setup.bash` script to allow the bash find the executables for ros2 nodes.

Also please make sure that if you are using a specific tag, use the same git source code version. If you check that specific README (https://github.com/analogdevicesinc/tof-ros2/tree/v4.3.0) you can see that the node name has changed. In your example you were trying to start with the new node name, while it should be the same, old one
` ros2 run tof_ros2cpp tof_ros2cpp ...`

**Comment by Genozen** [comment]
Yes, I did try the `source install/local_setup.bash`  as well    @rbudai98 

I followed that code version of the readme:
`ros2 run tof_ros2cpp tof_ros2cpp ip=10.42.0.1 config_file=config/config_adsd3500_adsd3030_new_modes.json mode=0`
but got
```
I20231219 16:36:44.945358 16080 aditof_utils.cpp:94] Started camera intialization
I20231219 16:36:44.945601 16080 system_impl.cpp:92] SDK built with websockets version:3.1.0
I20231219 16:36:44.945641 16080 usb_sensor_enumerator.cpp:61] Looking for USB connected sensors
W20231219 16:36:45.060299 16080 aditof_utils.cpp:106] No cameras found
[ros2run]: Segmentation fault
```

Any ideas?

My viewer from the SDK works just fine, but I noticed in the mode settings it crashes if it's not `sr-mixed` or `lr-mixed`


![image](https://github.com/analogdevicesinc/tof-ros2/assets/74474611/343db419-5cec-40e3-a5b0-f20f78b7c97f)




The closest I've gotten it is when using the `main` branch... (https://github.com/analogdevicesinc/tof-ros2/issues/55#issuecomment-1862319325)


Also in the https://github.com/analogdevicesinc/tof-ros2/tree/v4.3.0, it's listing the Rel ver 4.2.0, but I have 4.3.0 as mentioned. It should be okay right?

![image](https://github.com/analogdevicesinc/tof-ros2/assets/74474611/5a34cb7f-2c6f-41ee-be54-5a245894f583)


And the analog@10.42.0.1 has:
![image](https://github.com/analogdevicesinc/tof-ros2/assets/74474611/6bb0b00d-1342-4604-af0c-183d8d1466e1)

**Comment by rbudai98** [comment]
Yes, the 4.3.0 version should be right. The built packages I think were just not updated at the moment of the tag.

Continuing from the last error you get, could you change one small thing in tof-ros2 in: https://github.com/analogdevicesinc/tof-ros2/blob/2e17d437d212be760d424676b4cdf8d186bd37d3/src/aditof_utils.cpp#L84
Change:
result[0] = ip;
To:
result[0] = std::string("ip:") + ip;

and after a fresh build try starting the node again. The ToF SDK and tof-ros2 seem to have some discrepancies at the same version. In cas this solves your problem I will update the tag to have this specific change.

**Comment by Genozen** [comment]
> Yes, the 4.3.0 version should be right. The built packages I think were just not updated at the moment of the tag.
> 
> Continuing from the last error you get, could you change one small thing in tof-ros2 in:
> 
> https://github.com/analogdevicesinc/tof-ros2/blob/2e17d437d212be760d424676b4cdf8d186bd37d3/src/aditof_utils.cpp#L84
> 
> Change:
> result[0] = ip;
> To:
> result[0] = std::string("ip:") + ip;
> 
> and after a fresh build try starting the node again. The ToF SDK and tof-ros2 seem to have some discrepancies at the same version. In cas this solves your problem I will update the tag to have this specific change.

I will give it a try this week.

**Comment by Genozen** [comment]
@rbudai98  This method works!! Thank you so much.

`Mode=0` and `1` will not work as stated in the document somewhere...

Could you tell me how to properly set the FPS?

My running script is `ros2 run tof_ros2cpp tof_ros2cpp ip=10.42.0.1 config_file=config/config_adsd3500_adsd3030_new_modes.json mode=6`


But when I modify the FPS parameter directing in the path, but the FPS is still capped at 10 FPS. I know it's possible to go as high as 50 FPS in the Analog software.

`config/config_adsd3500_adsd3030_new_modes.json`
```
{
    "VAUX_POWER_VOLTAGE": "18",
    "DEPTH_INI": "./config/RawToDepthAdsd3030_sr-native.ini;./config/RawToDepthAdsd3030_lr-native.ini;./config/RawToDepthAdsd3030_sr-qnative.ini;./config/RawToDepthAdsd3030_lr-qnative.ini;./config/RawToDepthAdsd3030_sr-mixed.ini;./config/RawToDepthAdsd3030_lr-mixed.ini;./config/RawToDepthAdsd_pcm-native.ini",
    "FPS": "60",
    "FSYNC_MODE": "1"
}
```

And is it possible to run long-range mixed with short-range?

The xyz scale in Rviz2 seems super large, is it a good practice to scale it down? (have to zoom all the way out and set size = 1 instead of 0.01)

**Comment by rbudai98** [comment]
Hi @Genozen!
Thanks for the feedback and glad it worked. I will update the tags according to this change.
The FPS indeed can be set within the json file. If run on NXP I don't recall the exact speed of the ROS2 publishing node (we can try doing some tests), but in case it is using SDK to transfer data with libwebsocket it is still limited between 10 - 15 fps.
Also the latest tof-ros2 master has improvements on this part (multithreading and safe topic publishing), maybe updating to that could help. (And you can disable threads such as xyz in case you don't wish to publish, increasing the performance of the rest of the nodes)

I don't really understand what you mean under "long-range mixed with short-range" together, but separately they definitely can be run.

The xyz scaling might be helpful for performance but also takes time the processing part, however we did not test it so far.

Best,
Robert

**Comment by Genozen** [comment]
@rbudai98 , sorry I'm still confused with the statement with the NXP and SDK.

So if I run the ros2 wrapper for the SDK, which is ros launch from my PC and grabs the data from the NXP dev board, the FPS will still be limited?

Any chance you could do the test and run ROS on the NXP dev board to know the actual FPS? I would like to eventually put the ToF sensor onto a SOM board... or could you guide me through and see how I can run ROS directly in the NXP dev board? I'm running a mapping algorithm on my PC, so the FPS is kind of crucial if the ROS2 wrapper cannot output higher FPS...


Regarding the "And is it possible to run long-range mixed with short-range?", what I meant was can I combine the ptcloud generated in the short-range (mode = 5) to the ptcloud generated in the long-range mode (mode = 6)? Basically, I want the full range of the ptcloud altogether...

**Comment by rbudai98** [comment]
Hi @Genozen!
If you want to connect the sensor to a custom SOM board (not NXP) than the fps indeed according to the sensor's datasheet can achieve higher than 50 fps. The SDK on the NXP has this 15 fps limitation over network. So if you launch the ros2 node from PC that has usb-c conneciton to the NXP, it will have this 15 fps limitation.

This [https://github.com/analogdevicesinc/tof-ros2/pull/52] can be helpful setting up ROS2 on NXP.

Regarding the mode combination I don't' think that it can be used in the same time. If you check the initialization process the mode is set previously to grab a frame. So using the long range and short range simultaneously would require alternating this mode setting that can reduce significantly the fps.

**Comment by Genozen** [comment]
Hi @rbudai98, just have a quick question regarding the pointclouds distances I'm getting in Rviz2. What are the units? They seem to not be in meters...

**Comment by rbudai98** [comment]
Hi @Genozen!
The point cloud values come directly from the SDK in milli-meter units.
