### ISSUE TITLE
docker not finding camera

### ISSUE THREAD

**Issue by dorhalperinM** [analogdevicesinc/tof-ros2#58]
getting error while runinng the ros docker. the camera is working in widows

running command: ros2 launch tof_ros2cpp EVAL-ADTF3175D.launch.xml
and getting
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-04-02-12-56-59-040932-dor-172
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [tof_ros2cpp_node-1]: process started with pid [173]
[tof_ros2cpp_node-1] I20240402 12:56:59.083928   173 aditof_utils.cpp:105] Started camera intialization
[tof_ros2cpp_node-1] I20240402 12:56:59.084060   173 system_impl.cpp:88] SDK built with websockets version:3.1.0
[tof_ros2cpp_node-1] I20240402 12:56:59.084081   173 network_sensor_enumerator.cpp:55] Looking for sensors over network: 10.42.0.1
[tof_ros2cpp_node-1] [2024/04/02 12:56:59:0882] NOTICE: Creating Vhost 'default' (serving disabled), 1 protocols, IPv6 off
[tof_ros2cpp_node-1] Server Message :: 
[tof_ros2cpp_node-1] W20240402 12:56:59.093889   173 network_sensor_enumerator.cpp:60] Server Connect Failed
[tof_ros2cpp_node-1] Connection Closed
[tof_ros2cpp_node-1] W20240402 12:56:59.094705   173 aditof_utils.cpp:114] No cameras found
[ERROR] [tof_ros2cpp_node-1]: process has died [pid 173, exit code -11, cmd '/ros2_ws/install/tof_ros2cpp/lib/tof_ros2cpp/tof_ros2cpp_node ip=10.42.0.1 config_file=config/config_adsd3500_adsd3100.json mode=2 --ros-args -r __node:=tof_ros2cpp'].

**Comment by rbudai98** [comment]
Hi @dorhalperinM!
The error seems to be on the connection part. Are you able to ping the 10.42.0.1 ip address from Docker file?

**Comment by dorhalperinM** [comment]
I check again and I get a successful ping within the docker to IP address 10.42.0.1.

**Comment by rbudai98** [comment]
In this case I would double check if the server on the camera is running with command:
`systemctl status network-gadget`
or in case it is started from user, checking in `top`

**Comment by dorhalperinM** [comment]
After using the command systemctl status network-gadget
I got
Unit network-gadget.service could not be found.

**Comment by rbudai98** [comment]
Than you might have to start the server manually:
 In dir: home/analog/Workspace/tof/build/apps/server run: `./aditof-server`

**Comment by dorhalperinM** [comment]
I can't find aditof-server and there is no server folder in the path home/analog/Workspace/tof/build/apps

**Comment by rbudai98** [comment]
Please refer to: https://github.com/analogdevicesinc/ToF/tree/main/apps/server
Since this is not ros2 related issue, for any further question please open an issue on: https://github.com/analogdevicesinc/ToF/

Best reagrds,
Robert Budai
